### ISSUE TITLE
Notification disappears without staying on notification panel.

### ISSUE THREAD

**Issue by AbRehman0346** [cb-cloud/flutter_in_app_notification#27]
It works perfectly, but I want a notification to stay at notification panel on phone. like a WhatsApp notification, which shows and then stays at notification panel. 
If there is a way to do this, Guide me.
Thanks.

**Comment by Kurogoma4D** [comment]
@AbRehman0346 
It's not possible on this package.
This works only in Flutter layer, not for use platform feature.

Alternatively, to stay notification on OS notification bar, you can use [flutter_local_notifications package](https://pub.dev/packages/flutter_local_notifications).
